export const mainPath = [
  { row: 6, col: 1 },
  { row: 6, col: 2 },
  { row: 6, col: 3 },
  { row: 6, col: 4 },
  { row: 6, col: 5 },
  { row: 5, col: 6 },
  { row: 4, col: 6 },
  { row: 3, col: 6 },
  { row: 2, col: 6 },
  { row: 1, col: 6 },
  { row: 0, col: 6 },
  { row: 0, col: 7 },
  { row: 0, col: 8 },
  { row: 1, col: 8 },
  { row: 2, col: 8 },
  { row: 3, col: 8 },
  { row: 4, col: 8 },
  { row: 5, col: 8 },
  { row: 6, col: 8 },
  { row: 7, col: 9 },
  { row: 7, col: 10 },
  { row: 7, col: 11 },
  { row: 7, col: 12 },
  { row: 7, col: 13 },
  { row: 7, col: 14 },
  { row: 8, col: 14 },
  { row: 9, col: 14 },
  { row: 10, col: 14 },
  { row: 11, col: 14 },
  { row: 12, col: 14 },
  { row: 13, col: 14 },
  { row: 14, col: 14 },
  { row: 14, col: 13 },
  { row: 14, col: 12 },
  { row: 13, col: 12 },
  { row: 12, col: 12 },
  { row: 11, col: 12 },
  { row: 10, col: 12 },
  { row: 9, col: 12 },
  { row: 8, col: 12 },
  { row: 7, col: 11 },
  { row: 7, col: 10 },
  { row: 7, col: 9 },
  { row: 7, col: 8 },
  { row: 7, col: 7 },
  { row: 7, col: 6 },
  { row: 7, col: 5 },
  { row: 7, col: 4 },
  { row: 7, col: 3 },
  { row: 7, col: 2 },
  { row: 7, col: 1 },
  { row: 7, col: 0 },
  { row: 6, col: 0 },
  { row: 5, col: 0 },
  { row: 4, col: 0 },
  { row: 3, col: 0 },
  { row: 2, col: 0 },
  { row: 1, col: 0 },
  { row: 0, col: 0 },
  { row: 0, col: 1 },
  { row: 0, col: 2 },
  { row: 0, col: 3 },
  { row: 0, col: 4 },
  { row: 0, col: 5 },
  { row: 1, col: 5 },
  { row: 2, col: 5 },
  { row: 3, col: 5 },
  { row: 4, col: 5 },
  { row: 5, col: 5 },
  { row: 6, col: 5 },
];

export const playerStartIndex = {
  Red: 0,
  Blue: 13,
  Green: 26,
  Yellow: 39,
};

export const victoryLanes = {
  Red: [
    { row: 6, col: 6 },
    { row: 5, col: 7 },
    { row: 4, col: 7 },
    { row: 3, col: 7 },
    { row: 2, col: 7 },
    { row: 1, col: 7 },
  ],
  Blue: [
    { row: 7, col: 8 },
    { row: 6, col: 9 },
    { row: 6, col: 10 },
    { row: 6, col: 11 },
    { row: 6, col: 12 },
    { row: 6, col: 13 },
  ],
  Green: [
    { row: 8, col: 8 },
    { row: 9, col: 7 },
    { row: 10, col: 7 },
    { row: 11, col: 7 },
    { row: 12, col: 7 },
    { row: 13, col: 7 },
  ],
  Yellow: [
    { row: 8, col: 6 },
    { row: 9, col: 5 },
    { row: 9, col: 4 },
    { row: 9, col: 3 },
    { row: 9, col: 2 },
    { row: 9, col: 1 },
  ],
};

export const homePositions = {
  Red: [
    { row: 1, col: 1 },
    { row: 1, col: 3 },
    { row: 3, col: 1 },
    { row: 3, col: 3 },
  ],
  Blue: [
    { row: 1, col: 11 },
    { row: 1, col: 13 },
    { row: 3, col: 11 },
    { row: 3, col: 13 },
  ],
  Green: [
    { row: 11, col: 11 },
    { row: 11, col: 13 },
    { row: 13, col: 11 },
    { row: 13, col: 13 },
  ],
  Yellow: [
    { row: 11, col: 1 },
    { row: 11, col: 3 },
    { row: 13, col: 1 },
    { row: 13, col: 3 },
  ],
};
