"""Add piece_id to Move model

Revision ID: 185e00a84c2d
Revises: cf1fe00bc513
Create Date: 2025-10-04 08:53:13.971539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '185e00a84c2d'
down_revision = 'cf1fe00bc513'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('piece_id', sa.Integer(), nullable=False, default=1))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moves', schema=None) as batch_op:
        batch_op.drop_column('piece_id')

    # ### end Alembic commands ###
